feat(scripts): add vpn kill

diff --git a/scripts/strongswan-with-tmux/vpn b/scripts/strongswan-with-tmux/vpn
--- a/scripts/strongswan-with-tmux/vpn
+++ b/scripts/strongswan-with-tmux/vpn
@@ -1,6 +1,18 @@
 #!/bin/bash
+# shellcheck disable=SC2086
 
 set -euo pipefail
+
+_deps=(
+  "tmux"
+  "fzf"
+)
+
+for dep in "${_deps[@]}"; do
+  if ! type $dep >/dev/null 2>&1; then
+    echo >&2 -e "vpn: $dep is required"
+  fi
+done
 
 vpn_endpoints=(
   development
@@ -10,6 +22,11 @@ vpn_endpoints=(
 
 get_choice() {
   choice=$(printf "%s\n" "${vpn_endpoints[@]}" | fzf)
+  echo -n $choice
+}
+
+get_choice_current_conn() {
+  choice=$(tmux list-sessions -F '#{session_name}' | grep -v main | fzf)
   echo -n $choice
 }
 
@@ -65,6 +82,18 @@ main() {
           fi
 
           [ -z ${TMUX:-} ] && tmux attach -t $host:99 || tmux switch -t $host:99
+        ;;
+        kill)
+          shift
+          [[ $# -eq 0 ]] && host=$(get_choice_current_conn) || host=$1
+
+          if ! tmux has-session -t $host 2>/dev/null; then
+            echo >&2 -e "vpn: there is no vpn connection established to $host"
+            exit 1
+          fi
+
+          echo >&2 -e "vpn: disconnecting from $host"
+          tmux kill-session -t $host 2>/dev/null
         ;;
         cleanup)
           echo >&2 -e "vpn: cleanup all vpn connection"
