Add persistent and cleanup support

diff --git a/kubectl/ssh-jump/ssh-jump b/kubectl/ssh-jump/ssh-jump
--- a/kubectl/ssh-jump/ssh-jump
+++ b/kubectl/ssh-jump/ssh-jump
@@ -17,6 +17,9 @@ SSH_IDENTITY_FILE="-"
 SSH_OPTS=""
 DESTINATION_NODE=""
 
+CLEANUP=""
+PERSISTENT_MODE=no
+
 EXIT=0
 
 usage() {
@@ -40,9 +43,47 @@ Flags:
   -p, --port          : Target SSH Port. Default "22".
   -i, --identity-file : Target SSH identity file.
   -o, --ssh-opts      : SSH additional flags.
+  --cleanup           : Clean up ssh-jump if any. This flag is mutually exclusive with `--persistent`.
+  --persistent        : Enable ssh-jump pod in persistent mode. This flag is mutually exclusive with `--cleanup`.
 EOF
 
 exit 0
+}
+
+sshpod_manifest(){
+cat << EOF
+apiVersion: v1
+kind: Pod
+metadata:
+  annotations:
+    ssh-jump.k8s.ardikabs.com/persistent: "${PERSISTENT_MODE}"
+    ssh-jump.k8s.ardikabs.com/destination: "$DESTINATION_NODE"
+    ssh-jump.k8s.ardikabs.com/ssh-username: "$SSH_USERNAME"
+    ssh-jump.k8s.ardikabs.com/ssh-port: "$SSH_PORT"
+    ssh-jump.k8s.ardikabs.com/ssh-identity-file: "${SSH_IDENTITY_FILE}"
+  name: $1
+  namespace: default
+  labels:
+    app: ssh-jump
+    usage: jumper
+spec:
+  containers:
+  - name: ssh-jump
+    image: corbinu/ssh-server
+    ports:
+    - containerPort: 22
+      protocol: TCP
+    resources:
+      limits:
+        cpu: 200m
+        memory: 256Mi
+      requests:
+        cpu: 100m
+        memory: 128Mi
+  restartPolicy: Never
+  tolerations:
+  - operator: Exists
+EOF
 }
 
 showErr(){
@@ -64,6 +105,7 @@ parseFlags(){
     # Parsing flags
     for arg in "$@"
     do
+        skip=0
         case $arg in
             -h|--help)
             usage
@@ -72,47 +114,52 @@ parseFlags(){
             if [[ "${arg#*=}" =~ ^- ]];
             then
                 SSH_USERNAME="$2"
-                shift # Remove --username from processing
-                shift # Remove username value from processing
+                skip=2
             else
                 SSH_USERNAME="${arg#*=}"
-                shift # Remove --username=* from processing
+                skip=1
             fi
             ;;
             -p=*|--port=*|-p|--port)
             if [[ "${arg#*=}" =~ ^- ]];
             then
                 SSH_PORT="$2"
-                shift # Remove --port from processing
-                shift # Remove port value from processing
+                skip=2
             else
                 SSH_PORT="${arg#*=}"
-                shift # Remove --port=* from processing
+                skip=1
             fi
             ;;
             -i=*|--identity-file=*|-i|--identity-file)
             if [[ "${arg#*=}" =~ ^- ]];
             then
                 SSH_IDENTITY_FILE="-i $2"
-                shift # Remove --identity-file from processing
-                shift # Remove identity-file value from processing
+                skip=2
             else
                 SSH_IDENTITY_FILE="-i ${arg#*=}"
-                shift # Remove --identity-file=* from processing
+                skip=1
             fi
             ;;
             -o=*|--ssh-opts=*|-o|--ssh-opts)
             if [[ "${arg#*=}" =~ ^- ]];
             then
                 SSH_OPTS="-i $2"
-                shift # Remove --ssh-opts from processing
-                shift # Remove ssh-opts value from processing
+                skip=2
             else
                 SSH_OPTS="-i ${arg#*=}"
-                shift # Remove --ssh-opts=* from processing
+                skip=1
             fi
             ;;
+            --cleanup)
+            CLEANUP=true
+            skip=1
+            ;;
+            --persistent)
+            PERSISTENT_MODE=yes
+            skip=1
+            ;;
         esac
+        shift $skip
     done
 
     # Parsing arguments
@@ -129,72 +176,56 @@ parseFlags(){
 }
 
 terminateSSHPod(){
-    echo ""
-    echo -e "Terminating pod/${POD_NAME}"
-    kill -2 ${pid_port_forward} >/dev/null 2>&1
-    kubectl delete pod ${POD_NAME} -n default --force --grace-period=0  2> /dev/null
-    exit $EXIT
-}
 
-sshpod_manifest(){
-cat << EOF
-apiVersion: v1
-kind: Pod
-metadata:
-  annotations:
-    ssh-jump.k8s.ardikabs.com/temporary: "true"
-    ssh-jump.k8s.ardikabs.com/destination: "$DESTINATION_NODE"
-    ssh-jump.k8s.ardikabs.com/ssh-username: "$SSH_USERNAME"
-    ssh-jump.k8s.ardikabs.com/ssh-port: "$SSH_PORT"
-    ssh-jump.k8s.ardikabs.com/ssh-identity-file: "${SSH_IDENTITY_FILE}"
-  name: $1
-  namespace: default
-spec:
-  containers:
-  - name: ssh-jump
-    image: corbinu/ssh-server
-    ports:
-    - containerPort: 22
-      protocol: TCP
-    resources:
-      limits:
-        cpu: 100m
-        memory: 100Mi
-      requests:
-        cpu: 100m
-        memory: 100Mi
-  restartPolicy: Never
-  tolerations:
-  - operator: Exists
-EOF
+    kill -2 ${pid_port_forward} >/dev/null 2>&1
+
+    if [[ -n $CLEANUP ]] && [[ ${PERSISTENT_MODE} = "no" ]]; then
+        echo ""
+        echo -e "Terminating pod/${POD_NAME}"
+        kubectl delete pod -l app=ssh-jump,usage=jumper -n default --force --grace-period=0  2> /dev/null
+        exit $EXIT
+    fi
 }
 
 main(){
 
     parseFlags "$@"
 
-    MAX_POD_CREATION_TIME=10
-    POD_NAME=sshjump-$(head /dev/urandom | LC_ALL=C tr -dc a-z0-9 | head -c 7 ; echo '')
+    previous_pod_exist=$(kubectl get pod -n default -l app=ssh-jump,usage=jumper --no-headers -o custom-columns=NAME:.metadata.name 2>/dev/null | head -n1)
 
-    # Install a temporary SSH-server jumper
-    echo "Creating SSH jump host (Pod)..."
+    if [[ -n ${previous_pod_exist} ]]; then
+        POD_NAME=$previous_pod_exist
 
-    sshpod_manifest $POD_NAME | kubectl apply -f -
+        echo "Use existing SSH jump host (${previous_pod_exist})"
 
-    trap terminateSSHPod SIGINT SIGTERM
+    else
+        MAX_POD_CREATION_TIME=10
+        POD_NAME=sshjump-$(head /dev/urandom | LC_ALL=C tr -dc a-z0-9 | head -c 7 ; echo '')
 
-    # Wait until sshjump gets ready
-    c=1
-    while [[ ${c} -le ${MAX_POD_CREATION_TIME} ]];
-    do
-        pod_status=$(kubectl get pod ${POD_NAME} -n default --no-headers 2>/dev/null | awk '{print $3}')
-        [ "${pod_status}" = "Running" ] && break
+        # Install a temporary SSH-server jumper
+        if [[ $PERSISTENT_MODE = "yes" ]]; then
+            echo "Creating persistent SSH jump host (Pod)..."
+        else
+            echo "Creating SSH jump host (Pod)..."
+        fi
 
-        (( c++ ))
-        sleep 1
+        sshpod_manifest $POD_NAME | kubectl apply -f -
 
-        [[ ${c} -gt ${MAX_POD_CREATION_TIME} ]] && { echo ""; echo -e "${RED}ERROR:${NC} Timeout exceeded while creating Pod ${POD_NAME}"; EXIT=1; terminateSSHPod; }
-    done
+        trap terminateSSHPod SIGINT SIGTERM
+
+        # Wait until sshjump gets ready
+        c=1
+        while [[ ${c} -le ${MAX_POD_CREATION_TIME} ]];
+        do
+            pod_status=$(kubectl get pod ${POD_NAME} -n default --no-headers -ocustom-columns=STATUS:.status.phase 2>/dev/null | head -n1)
+            [ "${pod_status}" = "Running" ] && break
+
+            (( c++ ))
+            sleep 1
+
+            [[ ${c} -gt ${MAX_POD_CREATION_TIME} ]] && { echo ""; echo -e "${RED}ERROR:${NC} Timeout exceeded while creating Pod ${POD_NAME}"; EXIT=1; terminateSSHPod; }
+        done
+    fi
 
     # Setup portforward
     if [ `uname -s` = Linux ]; then
